version: '3.2'

services:
  web:
    image: franela/watch-docker:${TAG:-latest}
    command: ./watch-docker
    environment:
      - PORT=3000
    labels:
      - traefik.backend=watch-docker
      - traefik.frontend.rule=Host:watch-docker.com
      - traefik.frontend.rule=Host:www.watch-docker.com
      - traefik.frontend.passHostHeader=true
      - traefik.frontend.entryPoints=http,https
      - traefik.port=3000
      - traefik.enable=true
    networks:
      - frontend

  mongo:
    image: mongo
    volumes:
      - mongo:/data/db

volumes:
  mongo:

networks:
  frontend:
    external: true
