version: '3.2'

services:
  web:
    build: ./
    command: gin
    ports:
      - 3000:3000
    volumes:
      - ./:/go/src/github.com/franela/watch-docker

  mongo:
    image: mongo
    volumes:
      - mongo:/data/db

volumes:
  mongo:
