version: '3.2'

services:
  web:
    build: ./
    command: gin
    ports:
      - 3000:3000
    volumes:
      - $GOPATH/src:/go/src

  mongo:
    image: mongo
    volumes:
      - mongo:/data/db

volumes:
  mongo:
